### ISSUE TITLE
translation to Dutch

### ISSUE THREAD

**Issue by Joppla** [forrestguice/SuntimesCalendars#29]
If you like I can make a translation to Dutch for the calendar app. But please tell me how or better, prepare the file.

**Comment by forrestguice** [comment]
Thank you. If you'd like to translate the app to Dutch, I'm glad to accept.

In preparation I've added [`values-nl/strings.xml`](https://github.com/forrestguice/SuntimesCalendars/blob/dutch-translation/app/src/main/res/values-nl/strings.xml) to the [`dutch-translation`](https://github.com/forrestguice/SuntimesCalendars/tree/dutch-translation) branch. You'll need to check out this branch, modify that file, and then submit a pull request. The guidelines [here](https://github.com/forrestguice/SuntimesWidget/blob/master/CONTRIBUTING.md#translations) apply; e.g. not modifying stuff between `xliff` tags, etc. 

I'm also happy to answer any questions (the comments in the file are pretty sparse, I apologize for that). You will actually be the first to directly translate the calendar addon. The other translations were migrated from the main app (but adding a full translation there is a huge task).

**Comment by Joppla** [comment]
Translation is finished, please check the comments.
