### ISSUE TITLE
feature request: add calendars individually

### ISSUE THREAD

**Issue by nutpantz** [forrestguice/SuntimesCalendars#3]
It would be nice if there was a choice to add each separate category individually solstice, equinoxes and moon phases.
Say you only wanted solstices and moon phases but not equinoxes, or only moon phases or soldiers and equinoxes..

**Comment by forrestguice** [comment]
Good suggestion. This is the direction I was thinking the app might develop. 

I was also thinking of adding the sunrise/sunset/twilight times too, but that's a lot of calendar entries, and maybe clutter. An option to choose the individual calendars is definitely needed.
