### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by Joppla** [forrestguice/SuntimesCalendars#32]
Hi,

I saw that the new version is availible on frdroid. It looks good. I will do soon a few modifications (spelling mistakes and so on). If you like I can make also a translation for the main app I you will prepare the file and will send me the link.

Jop

**Comment by forrestguice** [comment]
I really appreciate your offer, thank you. 
Translating the main app is a lot of work, so please translate as much or as little as you like (there's no need to finish it all in one go).

I've created a [`dutch-translation`](https://github.com/forrestguice/SuntimesWidget/tree/dutch-translation) branch with necessary preparations, and copied some values from SuntimesCalendars (https://github.com/forrestguice/SuntimesWidget/commit/0ca60baf2ee23c61d35ed3b2e44ed6943744bb24). 

You will need to checkout this branch, modify the [`values-nl/strings.xml`](https://github.com/forrestguice/SuntimesWidget/blob/dutch-translation/app/src/main/res/values-nl/strings.xml) file, and then submit a pull request. If you have any questions about specific strings (context, etc), don't hesitate to ask.

**Comment by Joppla** [comment]
I ve done a part, Question: Lunar noon, can you explain me what it is? Which moment in the cyclus?

**Comment by forrestguice** [comment]
This refer to the daily midpoint between moonrise and moonset (when the moon should be highest in the sky). Its similar to "solar noon" except for the moon. I think its mainly a curiosity - hunting/fishing prediction uses it, maybe there are other use cases.. Same for "lunar midnight".
