### ISSUE TITLE
Exporting Calendar Data?

### ISSUE THREAD

**Issue by tmr83** [forrestguice/SuntimesCalendars#48]
Hello,

Thank you for the excellent app. Is there an easy way to export the calendar data to add into Google Calendar or Gnome Calendar? I currently do not have an Android device, so I thought I could run Android in an emulator on Linux, but I don't have a good system for that.

**Comment by forrestguice** [comment]
I think any app that can write an `.ics` file should do the trick. Both Google Calendar and Gnome Calendar should support that.

I just tried https://f-droid.org/packages/org.sufficientlysecure.ical/ and was able to export and then reimport one of the `LOCAL` calendars that SuntimesCalendars manages. It seemed to hang for a minute, but eventually produced the file.

**Comment by tmr83** [comment]
Yes, that worked well.
