### ISSUE TITLE
import not populating calendar app

### ISSUE THREAD

**Issue by ghost** [forrestguice/SuntimesCalendars#58]
open suntimes calendar 0.6.0 select moon and solstice options then slide calendar integration after the process is done without any errors open the calendar app yet do not see the supplied events 

Suntimes (5) Android 10

**Comment by forrestguice** [comment]
Which calendar app are you using? 

Is it "Simple Calendar" by chance (or one of its forks)? I think early versions of this app lacked support, but the latest version should work, but only after enabling "CalDAV sync" (from Simple Calendar settings).

It should work automatically in Etar, or when using the default calendar app.

**Comment by ghost** [comment]
Simple Calendar, before reporting this as a bug I had turned on calendar storage which was made for Google I guess but "CalDAV sync" does the trick.
It looks like this is not an actual Suntimes bug however the intention here was to import a full daily moon phase and Suntimes calendar is disappointing only showing quarterlys.

**Comment by forrestguice** [comment]
> however the intention here was to import a full daily moon phase and Suntimes calendar is disappointing only showing quarterlys.

The four major phases are instants that occur at some specific time (easy to schedule), while the minor phases are all the moments in between. That is why they aren't part of the "moon phase" calendar.

It is possible to attach this information to other events though (like moonrise and moonset), so I've added support in `v0.6.1` for `%phase` and `illum` patterns to the "moon" calendar template. Note that it requires Suntimes `v0.15.11`. Also, you might need to "restore defaults" to get the patterns to appear, or add them manually if you've customized the template.
