### ISSUE TITLE
Feature Request: Calendar-Selection when more than one Calendar-App is installed ...

### ISSUE THREAD

**Issue by volker001** [forrestguice/SuntimesCalendars#63]
Let the user chose in which Calendar-App he want to import the Suntimes Calendar, when there are more than one Calendar-Apps is installed.
For example the Default-Android Etar Calendar App is installed and a second one the Fossify-Calendar.
The Etar Calendar is the default Calendar, and all the Suntimes Calendar should go to the Fossify-Calendar-App.

**Comment by forrestguice** [comment]
Is the goal to display the Suntimes calendars from the Fossify-Calendar app? I think this is possible already.

Try this from within Fossify-Calendar.. Make sure that `: -> Settings -> CalDAV -> CalDAV sync` is checked, then `: -> Refresh CalDAV calendars`. Afterward the Suntimes calendars should show up in the filter list.

I think one of the big differences between an app like Fossify-Calendar and Etar (and others) is that Etar uses the built-in CalDAV interface provided by the OS, while Fossify-Calendar implements its own calendar database. Suntimes Calendars itself works by publishing calendars to the built-in interface provided by the OS.

**Comment by forrestguice** [comment]
I double checked those instructions - you will also need need to `: -> Settings -> CalDAV -> Manage synced calendars` too.
So the process is something like..
1. add the calendars from Suntimes Calendars.
2. from Fossify-Calendar;  check `: -> Settings -> CalDAV -> CalDAV sync`.
3. then  `: -> Settings -> Manage synced calendars` and check the Suntimes calendars.
4. then  `: -> Refresh CalDAV calendars`. 
5. Finally look in the filter list to show/hide the events.

**Comment by volker001** [comment]
It works, thank you.
